import { mutation } from "./_generated/server";

export default mutation({
  args: {},
  handler: async (ctx) => {
    // Clear everything first
    const allIdeas = await ctx.db.query("ideas").collect();
    for (const idea of allIdeas) await ctx.db.delete(idea._id);
    const allCats = await ctx.db.query("categories").collect();
    for (const cat of allCats) await ctx.db.delete(cat._id);
    const allTags = await ctx.db.query("tags").collect();
    for (const tag of allTags) await ctx.db.delete(tag._id);
    const allSections = await ctx.db.query("ideaSections").collect();
    for (const s of allSections) await ctx.db.delete(s._id);

    const now = Date.now();

    // 1. Admin
    let admin = await ctx.db.query("users").withIndex("by_email", (q) => q.eq("email", "admin@automatedworlds.com")).first();
    let adminId;
    if (!admin) {
      adminId = await ctx.db.insert("users", {
        clerkId: "seed_admin",
        email: "admin@automatedworlds.com",
        name: "AutomatedWorlds Admin",
        role: "admin",
        plan: "pro",
        totalPurchases: 0,
        totalSpent: 0,
        savedIdeas: [],
        onboardingComplete: true,
        createdAt: now,
        updatedAt: now,
      });
    } else {
      adminId = admin._id;
    }

    // 2. Categories
    const catSaasId = await ctx.db.insert("categories", { name: "SaaS", slug: "saas", description: "SaaS business ideas", icon: "🚀", color: "#6366f1", sortOrder: 1, isActive: true, createdAt: now });
    const catAiId = await ctx.db.insert("categories", { name: "AI Tools", slug: "ai-tools", description: "AI products", icon: "🤖", color: "#8b5cf6", sortOrder: 2, isActive: true, createdAt: now });
    const catEcomId = await ctx.db.insert("categories", { name: "E-commerce", slug: "ecommerce", description: "Online retail", icon: "🛒", color: "#f59e0b", sortOrder: 3, isActive: true, createdAt: now });
    const catDevId = await ctx.db.insert("categories", { name: "DevTools", slug: "devtools", description: "Dev tools", icon: "🛠️", color: "#10b981", sortOrder: 4, isActive: true, createdAt: now });
    const catMktId = await ctx.db.insert("categories", { name: "Marketing", slug: "marketing", description: "Growth tools", icon: "📈", color: "#ec4899", sortOrder: 5, isActive: true, createdAt: now });

    // 3. Tags
    const tB2B = await ctx.db.insert("tags", { name: "B2B", slug: "b2b", usageCount: 5, createdAt: now });
    const tAI = await ctx.db.insert("tags", { name: "AI", slug: "ai", usageCount: 4, createdAt: now });
    const tNoCode = await ctx.db.insert("tags", { name: "No-Code", slug: "no-code", usageCount: 3, createdAt: now });
    const tSaaS = await ctx.db.insert("tags", { name: "SaaS", slug: "saas", usageCount: 10, createdAt: now });

    // 4. Ideas
    const ideasData = [
      {
        title: "Micro-SaaS for Gym Retention",
        slug: "gym-retention-saas",
        tagline: "Automated outreach to stop churn.",
        description: "Personalized SMS and email drips for independent gyms.",
        categoryId: catSaasId,
        tagIds: [tB2B, tSaaS],
        status: "published" as const,
        visibility: "public" as const,
        isFeatured: true,
        isNew: true,
        targetAudience: "Gym owners",
        problemStatement: "High 90-day churn.",
        solutionOverview: "Automated drips.",
        uniqueValueProp: "Gym-specific triggers.",
        competitors: [{ name: "Mindbody", weakness: "Poor retention" }],
        revenueModel: "Monthly sub",
        revenueStreams: ["Subscriptions"],
        techStack: [{ name: "Next.js", role: "Frontend" }],
        difficulty: "beginner" as const,
        roiPotential: "high" as const,
        priceCodeBase: 19900,
        priceCustomization: 49900,
        viewCount: 1200,
        saveCount: 45,
        purchaseCount: 12,
        reviewCount: 3,
        rating: 4.8,
        screenshotIds: [],
      },
      {
        title: "AI RFP Responder",
        slug: "ai-rfp-responder",
        tagline: "Write winning bids in hours, not weeks.",
        description: "Generative AI for enterprise sales RFPs.",
        categoryId: catAiId,
        tagIds: [tAI, tB2B],
        status: "published" as const,
        visibility: "public" as const,
        isFeatured: false,
        isNew: true,
        targetAudience: "Sales teams",
        problemStatement: "RFPs are too manual.",
        solutionOverview: "AI bid draft engine.",
        uniqueValueProp: "Custom RAG history.",
        competitors: [{ name: "Loopio", weakness: "No generative AI" }],
        revenueModel: "SaaS",
        revenueStreams: ["Subscriptions"],
        techStack: [{ name: "OpenAI", role: "LLM" }],
        difficulty: "advanced" as const,
        roiPotential: "very_high" as const,
        priceCodeBase: 49900,
        priceCustomization: 99900,
        viewCount: 850,
        saveCount: 89,
        purchaseCount: 0,
        reviewCount: 0,
        rating: 0,
        screenshotIds: [],
      },
      {
        title: "Shopify Returns Portal",
        slug: "shopify-returns-portal",
        tagline: "Self-serve returns for Shopify brands.",
        description: "Branded portal to handle returns automatically.",
        categoryId: catEcomId,
        tagIds: [tSaaS],
        status: "published" as const,
        visibility: "public" as const,
        isFeatured: false,
        isNew: false,
        targetAudience: "Shopify merchants",
        problemStatement: "Returns support is heavy.",
        solutionOverview: "Self-serve portal.",
        uniqueValueProp: "Affordable for SMBs.",
        competitors: [{ name: "Loop", weakness: "Expensive" }],
        revenueModel: "Flat fee",
        revenueStreams: ["SaaS"],
        techStack: [{ name: "Next.js", role: "Frontend" }],
        difficulty: "intermediate" as const,
        roiPotential: "medium" as const,
        priceCodeBase: 14900,
        priceCustomization: 39900,
        viewCount: 3400,
        saveCount: 156,
        purchaseCount: 42,
        reviewCount: 15,
        rating: 4.5,
        screenshotIds: [],
      },
      {
        title: "Automated SEO Audit Tool",
        slug: "seo-audit-automation",
        tagline: "Weekly technical SEO audits delivered to Slack.",
        description: "Monitors site health and SEO performance automatically.",
        categoryId: catMktId,
        tagIds: [tB2B, tSaaS],
        status: "published" as const,
        visibility: "public" as const,
        isFeatured: true,
        isNew: false,
        targetAudience: "Agencies and site owners",
        problemStatement: "Manual SEO audits are time-consuming.",
        solutionOverview: "Automated crawler and reporting.",
        uniqueValueProp: "Slack-first delivery.",
        competitors: [{ name: "Ahrefs", weakness: "Complex UI" }],
        revenueModel: "Per-site subscription",
        revenueStreams: ["SaaS"],
        techStack: [{ name: "Convex", role: "Backend" }],
        difficulty: "intermediate" as const,
        roiPotential: "high" as const,
        priceCodeBase: 24900,
        priceCustomization: 60000,
        viewCount: 2100,
        saveCount: 78,
        purchaseCount: 15,
        reviewCount: 5,
        rating: 4.7,
        screenshotIds: [],
      },
      {
        title: "AI Interior Design Studio",
        slug: "ai-interior-design",
        tagline: "Redesign your room in seconds with a single photo.",
        description: "Generates high-quality interior design renders from photos.",
        categoryId: catAiId,
        tagIds: [tAI, tNoCode],
        status: "published" as const,
        visibility: "public" as const,
        isFeatured: false,
        isNew: true,
        targetAudience: "Homeowners and realtors",
        problemStatement: "Interior designers are expensive.",
        solutionOverview: "AI image-to-image generation.",
        uniqueValueProp: "Zero cost for initial renders.",
        competitors: [{ name: "InteriorAI", weakness: "Low resolution" }],
        revenueModel: "Credits-based",
        revenueStreams: ["Credits"],
        techStack: [{ name: "Replicate", role: "AI API" }],
        difficulty: "beginner" as const,
        roiPotential: "medium" as const,
        priceCodeBase: 9900,
        priceCustomization: 20000,
        viewCount: 5600,
        saveCount: 320,
        purchaseCount: 8,
        reviewCount: 2,
        rating: 4.2,
        screenshotIds: [],
      },
      {
        title: "Headless CMS for Personal Brands",
        slug: "personal-brand-cms",
        tagline: "Manage your blog, newsletter, and links in one place.",
        description: "A simple, fast headless CMS built for individuals.",
        categoryId: catDevId,
        tagIds: [tSaaS, tNoCode],
        status: "published" as const,
        visibility: "public" as const,
        isFeatured: false,
        isNew: false,
        targetAudience: "Influencers and writers",
        problemStatement: "Fragmented content across multiple platforms.",
        solutionOverview: "Unified CMS dashboard.",
        uniqueValueProp: "Built-in newsletter tools.",
        competitors: [{ name: "Ghost", weakness: "Too complex for some" }],
        revenueModel: "Monthly SaaS",
        revenueStreams: ["SaaS"],
        techStack: [{ name: "Next.js", role: "Frontend" }],
        difficulty: "beginner" as const,
        roiPotential: "medium" as const,
        priceCodeBase: 12900,
        priceCustomization: 30000,
        viewCount: 1500,
        saveCount: 42,
        purchaseCount: 20,
        reviewCount: 4,
        rating: 4.6,
        screenshotIds: [],
      },
      {
        title: "Micro-Influencer Marketplace",
        slug: "micro-influencer-market",
        tagline: "Connect with authentic creators with 1k-10k followers.",
        description: "Platform for brands to find and hire small creators.",
        categoryId: catEcomId,
        tagIds: [tB2B],
        status: "published" as const,
        visibility: "public" as const,
        isFeatured: false,
        isNew: true,
        targetAudience: "E-commerce brands",
        problemStatement: "Big influencers are too expensive.",
        solutionOverview: "Database of micro-creators.",
        uniqueValueProp: "Verified engagement data.",
        competitors: [{ name: "Aspire", weakness: "Entry fee too high" }],
        revenueModel: "Transaction fee",
        revenueStreams: ["Fee", "Sub"],
        techStack: [{ name: "Clerk", role: "Auth" }],
        difficulty: "intermediate" as const,
        roiPotential: "high" as const,
        priceCodeBase: 34900,
        priceCustomization: 70000,
        viewCount: 2800,
        saveCount: 110,
        purchaseCount: 5,
        reviewCount: 1,
        rating: 5.0,
        screenshotIds: [],
      },
      {
        title: "Code Snippet Marketplace",
        slug: "snippet-marketplace",
        tagline: "Buy and sell production-ready UI components.",
        description: "A specialized store for Tailwind and Shadcn components.",
        categoryId: catDevId,
        tagIds: [tNoCode, tSaaS],
        status: "published" as const,
        visibility: "public" as const,
        isFeatured: true,
        isNew: false,
        targetAudience: "Developers",
        problemStatement: "Building UI from scratch is slow.",
        solutionOverview: "Component marketplace.",
        uniqueValueProp: "Copy-paste ready code.",
        competitors: [{ name: "TailwindUI", weakness: "Fixed library" }],
        revenueModel: "One-time purchase",
        revenueStreams: ["Sales"],
        techStack: [{ name: "Next.js", role: "Frontend" }],
        difficulty: "beginner" as const,
        roiPotential: "medium" as const,
        priceCodeBase: 19900,
        priceCustomization: 40000,
        viewCount: 4300,
        saveCount: 210,
        purchaseCount: 85,
        reviewCount: 24,
        rating: 4.9,
        screenshotIds: [],
      },
      {
        title: "AI Voice Translation for Creators",
        slug: "ai-voice-translation",
        tagline: "Translate your YouTube videos into 20 languages instantly.",
        description: "AI-powered dubbing and translation for video content.",
        categoryId: catAiId,
        tagIds: [tAI, tSaaS],
        status: "published" as const,
        visibility: "public" as const,
        isFeatured: false,
        isNew: true,
        targetAudience: "YouTubers",
        problemStatement: "Global audiences are hard to reach.",
        solutionOverview: "AI voice cloning and translation.",
        uniqueValueProp: "Matches your original voice tone.",
        competitors: [{ name: "Rask.ai", weakness: "High subscription cost" }],
        revenueModel: "Usage-based",
        revenueStreams: ["Usage"],
        techStack: [{ name: "ElevenLabs", role: "Voice API" }],
        difficulty: "advanced" as const,
        roiPotential: "high" as const,
        priceCodeBase: 59900,
        priceCustomization: 120000,
        viewCount: 6700,
        saveCount: 450,
        purchaseCount: 10,
        reviewCount: 2,
        rating: 4.8,
        screenshotIds: [],
      }
    ];

    for (const ideaData of ideasData) {
      const ideaId = await ctx.db.insert("ideas", {
        ...ideaData,
        authorId: adminId,
        createdAt: now,
        updatedAt: now,
      });

      // Add common sections
      await ctx.db.insert("ideaSections", {
        ideaId,
        type: "metrics_grid",
        title: "Opportunity Scorecard",
        content: JSON.stringify([
          { label: "Market Demand", value: "High" },
          { label: "Difficulty", value: ideaData.difficulty },
          { label: "ROI Potential", value: ideaData.roiPotential },
          { label: "Est. Setup Time", value: "2-4 weeks" },
        ]),
        sortOrder: 1,
        isVisible: true,
        createdAt: now,
        updatedAt: now,
      });

      await ctx.db.insert("ideaSections", {
        ideaId,
        type: "feature_list",
        title: "Core Features",
        content: JSON.stringify([
          { title: "Ready-to-deploy Code", description: "Fully functional Next.js/Convex codebase." },
          { title: "Authentication Ready", description: "Clerk integration pre-configured." },
          { title: "Payment Integration", description: "Stripe/Polar billing hooks ready." },
        ]),
        sortOrder: 2,
        isVisible: true,
        createdAt: now,
        updatedAt: now,
      });

      await ctx.db.insert("ideaSections", {
        ideaId,
        type: "markdown",
        title: "Problem & Solution",
        content: `### Problem\n${ideaData.problemStatement}\n\n### Solution\n${ideaData.solutionOverview}`,
        sortOrder: 3,
        isVisible: true,
        createdAt: now,
        updatedAt: now,
      });
    }

    return "Seeded v3 successfully with rich sections.";
  },
});
